# Generated by Django 3.2.15 on 2022-09-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetDailyTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(max_length=5)),
                ('acceptance_rate_perc', models.FloatField(max_length=1)),
                ('driver_cancellation_rate', models.FloatField(max_length=1)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('car_id', models.IntegerField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
