# Generated by Django 3.2.15 on 2022-09-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetdailytrips',
            name='cash_collected',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fleetdailytrips',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='fleetdailytrips',
            name='fare_total',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fleetdailytrips',
            name='hours_online',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fleetdailytrips',
            name='toll',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fleetdailytrips',
            name='total_km',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='fleetdailytrips',
            name='trips',
            field=models.IntegerField(default=None),
        ),
    ]
