# Generated by Django 3.2.15 on 2022-09-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220912_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetdailytrips',
            name='acceptance_rate_perc',
            field=models.FloatField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='fleetdailytrips',
            name='car_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fleetdailytrips',
            name='driver_cancellation_rate',
            field=models.FloatField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='fleetdailytrips',
            name='driver_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fleetdailytrips',
            name='rating',
            field=models.FloatField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='fleetdailytrips',
            name='team_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
