# Generated by Django 3.2.15 on 2022-09-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220912_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleetdailytrips',
            options={'ordering': ['id']},
        ),
    ]
